---
title: "Project Proposal"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project Description

For our group project, members **Laurel Hecker**, **Hunter Francia**, 
**Jack Weinstein**, and **Tim Manalo** will be creating a Shiny webapp for data
visualization of information about movie earnings and ratings. 

### Datasets
We will be using two different APIs for this: [Box Office Report](https://market.mashape.com/udayogra/box-office-report) and 
[Rotton Tomatoes](https://www.programmableweb.com/api/rotten-tomatoes). The 
**Box Office Report** API was collected by user 
[UDAYOGRA](https://market.mashape.com/udayogra) on the website
[marketplace](https://market.mashape.com/), which hosts a variety of APIs. The
**Box Office Report** API includes the revenue for Hollywood movies by opening
day, opening weekend, and lifetime earnings. The **Rotten Tomatoes** API was
created by the movie review website [Rotton Tomatoes](https://www.rottentomatoes.com/), and will give access to various
review information, such as star ratings, year released, genre, and more.

### Target Audience

Our target audience is fellow movie-goers who are interested in movies trends
and success/failure rates.

### Specific Questions

Combining the **Box Office Report** API and **Rotten Tomatoes** API, we hope to
answer questions such as:

* What is the correlation between a movie's financial success and positive 
reviews?
    + Are there any outliers, such as movies which did well at the box office but
    flopped in terms of reviews, or vice versa?
* Are certain types of movies more popular during certain times of the year?
    + We will look at the frequency of various genres of movies during different
    months of the year, and compare that to whether they were well received both
    at the box office and in terms of positive reviews.
* Is a movie's opening weekend indicative of its overall earnings?
    + We will compare movies' earnings at the opening day, opening weekend, 
    and lifetime to see if success on the first day of the box office
    determines lifetimes success. 

## Technical Description
Below is a description of some of the more technical aspects of the project,
such as how we will be sourcing the data, what type of data wrangling we will 
be expecting, etc. 

### Data
As stated above, we will be reading in data from two seperate APIs, 
**Box Office Report** and **Rotten Tomatoes**. 

### Data-Wrangling
Throughout our project, we predict having to perform data wrangling such as:

* Join the tables from the **Box Office Report** and **Rotten Tomatoes** APIs.
* Selecting only titles which appear in both **Box Office Report** and 
**Rotten Tomatoes**
* Create a new column which will allow us to sort the movies by decades, so we/
the user can observe trands over time.
* Create multiple plots comparing **box office revenue** over *opening day*, 
*opening weekend*, and *lifetime revenue* to the ratings of said movie (based
on a system of 1-5 stars)
* Create a bar chart illustrating the *lifetime earnings* of a movie, with a
fill which will illustrate how much of that money was earned on *opening day*
and over *opening weekend*. 
* Create a data visualization which displays what a movies are organized by the 
*month* in which they were released, which also displays their *genre*,
*earnings*, and *star ratings*.
* Create a page which allows users to search by movie and will generate
information about the plot summary, five reviews, the average rating, and the
earnings. 

### Major/New Libraries
With this project, we will mostly be focusing on libraries we have already
learned such as **dplyr**, **ggplot**, and possibly **plotly** in order to 
improve our literacy in these libraries, as well as **Shiny** in order to build 
our web application. We will also possibly be using **lubridate**, in order to calculate dates within our data, such as how long ago a movie was released. 

### Major Challenges
The major challenges we anticapte mostly revolve around working with **Shiny**
to create a webapp which updates in real time, correctly conveys the information
from our data sets, and which a user can interact with intuitively. We are also
anticipating possible challenges with **collaborating over github**, but we hope
that because we are anticipating some challenges with these things we will be 
better prepared and equipped to handle what problems come our way. 